default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  - joint_name: joint_1
      has_velocity_limits: true
      max_velocity: 10.0
      max_acceleration_limits: false
      max_acceleration: 0.0
      
  - joint_name: joint_2
      has_velocity_limits: true
      max_velocity: 10.0
      max_acceleration_limits: false
      max_acceleration: 0.0
    
  - joint_name: joint_3
      has_velocity_limits: true
      max_velocity: 10.0
      max_acceleration_limits: false
      max_acceleration: 0.0

  - joint_name: joint_4
      has_velocity_limits: true
      max_velocity: 10.0
      max_acceleration_limits: false
      max_acceleration: 0.0

  - joint_name: joint_5
      has_velocity_limits: true
      max_velocity: 10.0
      max_acceleration_limits: false
      max_acceleration: 0.0